---
title: "EM_MLE_Derivation"
format: pdf
editor: visual
header-includes: 
  - |
    \AtBeginDocument{
      \renewcommand{\r}[1]{\textcolor{red}{#1}}
      \renewcommand{\b}[1]{\textcolor{blue}{#1}}
    }
  - \usepackage{xcolor}
  - \usepackage{algorithm}
  - \usepackage{algpseudocode}
  - \usepackage{mathtools}
  - \usepackage{float}
  - \newcommand{\coleq}{\mathrel{\mathop:}=}
  - \newcommand{\ve}[1]{\textbf{#1}}
  - \newcommand{\field}[1]{\mathbb{#1}}
  - \newcommand{\defn}[1]{\emph{#1}}
  - \newcommand{\oneVect}[1]{#1}
  - \newcommand{\mat}[1]{\textbf{#1}}
  - \newcommand{\oneMat}[1]{#1}
  - \newcommand{\tensor}[1]{\mathcal{#1}}
  - \newcommand{\oneTensor}[1]{#1} 
  - \newcommand{\vs}[1]{\mathcal{#1}}
  #- \newcommand{\mn}[1]{{#1} \choose {#2}}
  #- \newcommand{\mn}[2]{\mathrel{\underset{\scriptstyle {#1}\,{#2}}{\times}}}
  #- \newcommand{\mn}[2]{\underset{\scriptsize\color{red}{#1}\,\color{blue}{#2}}{\times}}
  #- \newcommand{\mn}[2]{\mathbb{#1}}
  #- \newcommand{\mn}[2]{\sideset{_{\color{red}{#1}}}{_{\color{blue}{#2}}}{\boldsymbol{\times}}}
  - \newcommand{\mn}[2]{\sideset{_{#1}}{_{#2}}{\mathop{\boldsymbol{\times}}}}
  - \newtheorem{proposition}{Proposition}[section]
  - \newtheorem{proof}{Proof}[section]
---

This document will detail the derivations required for the MLEs of all of the tensor variate distributions.

## General Normal Variance-Mean Mixture

First, consider the generic structure where $X$ is generated from a normal variance-mean mixture. Under the Barndorff-Nielsen construction, we can create these draws using 

$$X = \mu + W \alpha + \sqrt{W} Z$$ 

where $\mu$ is a vector, $\alpha$ is a vector, $Z \sim N(0, \Sigma)$. The distribution of $W$ is what determines the distribution of $X$. 

Consider again the construction used to create $X$. If we knew the underlying latent draw $w$, then $X|W = w \sim N(\mu + w \alpha, w \Sigma)$. 

$$
\begin{aligned}
f_{X}(x) &= \int_{0}^{\infty} f_{X|W}(x|w) f_{W}(w) dw \\ 
&= \int_{0}^{\infty} (2\pi)^{-k/2} \det(w \Sigma)^{-1/2} \exp\left\{\frac{-1}{2} (x - \mu - w\alpha)^{T} (w \Sigma)^{-1} (x - \mu - w\alpha)\right\} f_{W}(w) dw \\
&= (2\pi)^{-k/2}\det(\Sigma)^{-1/2} \int_{0}^{\infty} w^{-k/2} \exp\left\{\frac{-1}{2w} (x - \mu - w\alpha)^{T} \Sigma^{-1} (x - \mu - w\alpha)\right\} f_{W}(w) dw \\
&= (2\pi)^{-k/2}\det(\Sigma)^{-1/2} \int_{0}^{\infty} w^{-k/2} \exp\left\{\frac{-1}{2w} \left[(x-\mu)^{T} \Sigma^{-1} (x-\mu) - 2 w\alpha^{T} \Sigma^{-1} (x-\mu) + w^{2} \alpha^{T} \Sigma^{-1} \alpha\right]\right\} f_{W}(w) dw \\
&= (2\pi)^{-k/2}\det(\Sigma)^{-1/2} \int_{0}^{\infty} w^{-k/2} \exp\left\{\frac{-(x-\mu)^{T} \Sigma^{-1} (x-\mu)}{2w} + \alpha^{T} \Sigma^{-1} (x - \mu) - \frac{w \alpha^{T} \Sigma^{-1} \alpha}{2}\right\} f_{W}(w) dw \\
&= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} \int_{0}^{\infty} w^{-k/2} \exp\left\{\frac{-(x-\mu)^{T} \Sigma^{-1} (x-\mu)}{2w} - \frac{w \alpha^{T} \Sigma^{-1} \alpha}{2}\right\} f_{W}(w) dw \\
\end{aligned}
$$

Now we want to use the following property:

$$
\int_{0}^{\infty} w^{\lambda - 1} \exp\left\{\frac{-1}{2} bw^{-1} - \frac{1}{2} aw \right\} dw = 2 \left(\frac{b}{a}\right)^{\lambda/2} K_{\lambda}(\sqrt{ab})
$$
{#eq-integrate}


Depending on the distribution of $w$, denoted by $f_{W}(w)$, we can obtain different results for the function after integrating out the dependence on $w$.

## Generalized Hyperbolic

In this case, let $W$ be from the generalized inverse Gaussian distribution denoted as $W \sim \text{GIG}(a, b, \lambda)$.

Thus, the density function of $W$ where $w > 0$ is 

$$f_{W}(w|a, b, \lambda) = \frac{(\frac{a}{b})^{\lambda/2} w^{\lambda - 1}}{2 K_{\lambda}(\sqrt{ab})} \exp\left\{\frac{-1}{2} \left(aw + \frac{b}{w}\right)\right\}$$

where 

$$K_{\lambda}(x) = \frac{1}{2} \int_{0}^{\infty} y^{\lambda - 1} \exp\left\{\frac{-x}{2}\left(y + \frac{1}{y}\right)\right\} dy$$

is the modified Bessel function of the third kind. Also, we restrict $a > 0, b > 0, \lambda \in \mathbb{R}$.

Now we can plug in $f_{W}(w)$ to our earlier expression.

$$
\begin{aligned}
f_{X}(x) &= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} \int_{0}^{\infty} w^{-k/2} \exp\left\{\frac{-(x-\mu)^{T} \Sigma^{-1} (x-\mu)}{2w} - \frac{w \alpha^{T} \Sigma^{-1} \alpha}{2}\right\} f_{W}(w) dw \\
&= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} 
\\ & \quad \int_{0}^{\infty} w^{-k/2} \frac{(\frac{a}{b})^{\lambda/2} w^{\lambda - 1}}{2 K_{\lambda}(\sqrt{ab})}  \exp\left\{\frac{-(x-\mu)^{T} \Sigma^{-1} (x-\mu)}{2w} - \frac{w \alpha^{T} \Sigma^{-1} \alpha}{2}\right\} \exp\left\{\frac{-1}{2} \left(aw + \frac{b}{w}\right)\right\} dw\\
&= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} \frac{(\frac{a}{b})^{\lambda/2}}{2 K_{\lambda}(\sqrt{ab})} \\ & \quad \int_{0}^{\infty} w^{\lambda-k/2-1}  \exp\left\{-\frac{(x-\mu)^{T} \Sigma^{-1} (x-\mu) + b}{2w} - \frac{w(\alpha^{T} \Sigma^{-1} \alpha + a)}{2}\right\} dw
\end{aligned}
$$

Now using @eq-integrate, if we let $\lambda^{*} = \lambda - \frac{k}{2}, a^{*} = \alpha^{T} \Sigma^{-1} \alpha + a$ and $b^{*} = (x-\mu)^{T} \Sigma^{-1} (x-\mu) + b$ we can obtain the following.

$$
\begin{aligned}
f_{X}(x) &= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} \frac{(\frac{a}{b})^{\lambda/2}}{2 K_{\lambda}(\sqrt{ab})} \\ & \quad 2 \left(\frac{(x-\mu)^{T} \Sigma^{-1} (x-\mu) + b}{\alpha^{T} \Sigma^{-1} \alpha + a}\right)^{\lambda/2 - k/4} K_{\lambda - k/2}
\left(\sqrt{[(x-\mu)^{T} \Sigma^{-1} (x-\mu) + b][\alpha^{T} \Sigma^{-1} \alpha + a]}\right) \\
&= (2\pi)^{-k/2} \det(\Sigma)^{-1/2} \exp\left\{\alpha^{T} \Sigma^{-1} (x - \mu)\right\} \frac{(\frac{a}{b})^{\lambda/2}}{K_{\lambda}(\sqrt{ab})} \\ & \quad \left(\frac{(x-\mu)^{T} \Sigma^{-1} (x-\mu) + b}{\alpha^{T} \Sigma^{-1} \alpha + a}\right)^{\lambda/2 - k/4} K_{\lambda - k/2}
\left(\sqrt{[(x-\mu)^{T} \Sigma^{-1} (x-\mu) + b][\alpha^{T} \Sigma^{-1} \alpha + a]}\right)
\end{aligned}
$$


This defines the generalized hyperbolic distribution. Thus, $X \sim GH(\mu, \Sigma, \alpha, a, b, \lambda)$.

### Conditional Distribution of $W$

Now we have the probability distribution functions for $X, X|W$, and $W$. For use in the EM algorithm, we are also interested in $W|X$. 

## Tensor Variate Skewed Distribution

In the tensor variate case, the normal variance mean mixture model is an efficient way to introduce skewness. A random tensor $\tensor{X}$ can be written as

$$\tensor{X}_{i} = \tensor{M} + W_{i} \tensor{A} + \sqrt{W_{i}} \tensor{V}_{i}$$

where $\tensor{M}$ is a location tensor, $\tensor{A}$ is a skewness tensor, $\tensor{V} \sim \mathcal{N}_{n^*}(\mathbb{O}, \bigotimes_{d=1}^{D} \Sigma_{d})$ and $W > 0$ is a positive random variable. The distribution of $\tensor{X}$ will depend on the distribution of $W$.

We are interested in obtaining the MLEs of the distribution $X$.

If we knew the latent values $W_{i}$, then the distribution of $X_{i}$ would be normal.

$$X_{i} | W_{i} = w_{i} \sim N_{p}(W_{i} A, W_{i} \otimes_{i=1}^k \Sigma_{k})$$

Let the distribution of $w$ be represented as $h(w)$. Then the joint density can be written as

$$f(X_{i}, W_{i}; \theta) = f(X_{i}|w_{i}) f(w_{i}).$$

Thus, we can represent the joint distribution as a product of the tensor variate normal PDF and the PDF of $W$.


