// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cp_c
Rcpp::List cp_c(Rcpp::NumericVector X, int R, int max_iter, double tol, Rcpp::Nullable<Rcpp::List> init, bool verbose);
RcppExport SEXP _tensortools_cp_c(SEXP XSEXP, SEXP RSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP initSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type init(initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cp_c(X, R, max_iter, tol, init, verbose));
    return rcpp_result_gen;
END_RCPP
}
// n_prod
Rcpp::NumericVector n_prod(Rcpp::NumericVector tensor, int n, Rcpp::NumericMatrix mat);
RcppExport SEXP _tensortools_n_prod(SEXP tensorSEXP, SEXP nSEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tensor(tensorSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(n_prod(tensor, n, mat));
    return rcpp_result_gen;
END_RCPP
}
// nm_prod
NumericVector nm_prod(NumericVector A, NumericVector B, int n, int m);
RcppExport SEXP _tensortools_nm_prod(SEXP ASEXP, SEXP BSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_prod(A, B, n, m));
    return rcpp_result_gen;
END_RCPP
}
// tensor_prod
NumericVector tensor_prod(NumericVector A, NumericVector B, bool simplify);
RcppExport SEXP _tensortools_tensor_prod(SEXP ASEXP, SEXP BSEXP, SEXP simplifySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_prod(A, B, simplify));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tensortools_cp_c", (DL_FUNC) &_tensortools_cp_c, 6},
    {"_tensortools_n_prod", (DL_FUNC) &_tensortools_n_prod, 3},
    {"_tensortools_nm_prod", (DL_FUNC) &_tensortools_nm_prod, 4},
    {"_tensortools_tensor_prod", (DL_FUNC) &_tensortools_tensor_prod, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tensortools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
