# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cp_c <- function(X, R = 2L, max_iter = 2000L, tol = 1e-3, init = NULL, verbose = FALSE) {
    .Call(`_tensortools_cp_c`, X, R, max_iter, tol, init, verbose)
}

#' n-mode product
#'
#' Compute the n-mode product of a tensor with a matrix.
#'
#' @param tensor An array representing the tensor.
#' @param n  An integer specifying the mode to multiply across.
#' @param mat A matrix of size \eqn{m \times n} to multiply with.
#'
#' @return An array: the result of the n-mode product.
#'
#' @details The \eqn{n}-mode matrix product of a tensor
#'          \eqn{\tensor{A} \in \field{k}^{I_1 \times I_2 \times ... \times I_n}}
#'          with a matrix \eqn{\mat{U} \in \field{k}^{J \times I_n}} is
#'          \deqn{(\tensor{A} \times_n \mat{U}) \in
#'          \field{k}^{I_1 \times ... \times I_{n-1} \times J \times I_{n+1} \times ... \times I_N}}
#'          with entries \deqn{(\tensor{A} \times_n \mat{U})_{i_1, ..., i_{n-1}, j, i_{n+1}, ... I_N} =
#'          \sum_{i_n = 1}^{I_n} a_{i_1, i_2, \dots, i_N} u_{j, i_n}.}
#'          The tensor and matrix share one mode in common, denoted here as \eqn{I_n}.
#'          This operation is also called the tensor times matrix product.
#'
#' @examples
#' a <- array(1:3, dim = c(3, 1, 1))
#' x <- matrix(4:9, nrow = 2, ncol = 3)
#' n_prod(a, 1, x)
#' @export
n_prod <- function(tensor, n, mat) {
    .Call(`_tensortools_n_prod`, tensor, n, mat)
}

#' nm-mode product
#'
#' Compute the nm-mode product of a tensor with a tensor.
#'
#' @param tensor_A An array representing the tensor A.
#' @param tensor_B An array representing tensor B.
#' @param n An integer specifying which mode of tensor A to multiply across.
#' @param m An integer specifying which mode of tensor B to multiply across.
#'
#' @return An array: the result of the nm-mode product between A and B.
#'
#' @examples
#' A <- matrix(c(1, 2, 3, 4), nrow = 2)
#' x <- matrix(c(5, 6), nrow = 2)
#' nm_prod(A, x, 1, 1)
#' @export
nm_prod <- function(A, B, n, m) {
    .Call(`_tensortools_nm_prod`, A, B, n, m)
}

#' tensor product
#'
#' Compute the tensor product of a tensor with a tensor
#'
#' @param tensor_A An array representing the tensor A.
#' @param tensor_B An array representing tensor B.
#' @param simplify A bool saying whether to simplify the output. Defaults to TRUE.
#'
#' @return An array: the result of the tensor product between A and B.
#'
#' @examples
#' A <- matrix(c(1, 2, 3, 4), nrow = 2)
#' x <- matrix(c(5, 6), nrow = 2)
#' tensor_prod(A, x)
#' @export
tensor_prod <- function(A, B, simplify = TRUE) {
    .Call(`_tensortools_tensor_prod`, A, B, simplify)
}

